// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHYowMvF97uNWy1DZHxVhihBeozh94DRA',
    appId: '1:971230705984:web:ed7c54c30c60d8d47ce2a5',
    messagingSenderId: '971230705984',
    projectId: 'flutterpro-a21f7',
    authDomain: 'flutterpro-a21f7.firebaseapp.com',
    storageBucket: 'flutterpro-a21f7.appspot.com',
    measurementId: 'G-CE6ELVCXPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcSTAclsedeLvEaPmJz77znB4hbwmmdIw',
    appId: '1:971230705984:android:93b173e69f7b60f37ce2a5',
    messagingSenderId: '971230705984',
    projectId: 'flutterpro-a21f7',
    storageBucket: 'flutterpro-a21f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCJgxmF7kPugcfUOinIRFindcJG0Ro-BU',
    appId: '1:971230705984:ios:c57799a660174fe77ce2a5',
    messagingSenderId: '971230705984',
    projectId: 'flutterpro-a21f7',
    storageBucket: 'flutterpro-a21f7.appspot.com',
    iosClientId: '971230705984-2le6a39cs5nkh1afci28e1irfs1b91af.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCJgxmF7kPugcfUOinIRFindcJG0Ro-BU',
    appId: '1:971230705984:ios:c57799a660174fe77ce2a5',
    messagingSenderId: '971230705984',
    projectId: 'flutterpro-a21f7',
    storageBucket: 'flutterpro-a21f7.appspot.com',
    iosClientId: '971230705984-2le6a39cs5nkh1afci28e1irfs1b91af.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterproject',
  );
}
