// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZM-dZiYtjhv14e6NS-d6xiSOCnXKcmbk',
    appId: '1:582043423782:web:4f3a020d1b1ad3edf582e7',
    messagingSenderId: '582043423782',
    projectId: 'weather-app-2c804',
    authDomain: 'weather-app-2c804.firebaseapp.com',
    storageBucket: 'weather-app-2c804.appspot.com',
    measurementId: 'G-T12EK9GNPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsRsXw3nIQ-v8-U4S_neI1KLFTBKkVv5E',
    appId: '1:582043423782:android:c71ba7efc70602f0f582e7',
    messagingSenderId: '582043423782',
    projectId: 'weather-app-2c804',
    storageBucket: 'weather-app-2c804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGoM6tajpMiUaemu1x_dkLU0YgvgdrgHc',
    appId: '1:582043423782:ios:0bd93af1901066daf582e7',
    messagingSenderId: '582043423782',
    projectId: 'weather-app-2c804',
    storageBucket: 'weather-app-2c804.appspot.com',
    iosClientId: '582043423782-8ggrvbhb9csg7thlmv9q59uencdek7c2.apps.googleusercontent.com',
    iosBundleId: 'com.example.weaterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGoM6tajpMiUaemu1x_dkLU0YgvgdrgHc',
    appId: '1:582043423782:ios:0bd93af1901066daf582e7',
    messagingSenderId: '582043423782',
    projectId: 'weather-app-2c804',
    storageBucket: 'weather-app-2c804.appspot.com',
    iosClientId: '582043423782-8ggrvbhb9csg7thlmv9q59uencdek7c2.apps.googleusercontent.com',
    iosBundleId: 'com.example.weaterapp',
  );
}
